server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otc_dev
    username: otc_user
    password: otc_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

otc:
  rules-service:
    base-url: http://localhost:8082
